### ISSUE TITLE
error while adding the package

### ISSUE THREAD

**Issue by prakas25** [meteor-utilities/menu#3]
While selecting package versions:
error: unknown package: isobuild:isopack-2
Required by: utilities:menu 0.1.6

I will appreciate a quick response

**Comment by SachaG** [comment]
Sorry, this package is not supported anymore :(

**Comment by prakas25** [comment]
can you suggest any good package for nested menu?

**Comment by SachaG** [comment]
I'd suggest using React and Bootstrap-React.
